# 服务器配置
server:
  port: 8080  # 服务端口号
  servlet:
    context-path: /api  # 应用上下文路径

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false  # 数据库连接URL
    username: root  # 数据库用户名
    password: root  # 数据库密码
    # 数据库连接池配置
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动类
    type: com.zaxxer.hikari.HikariDataSource  # 使用Hikari连接池
    # Hikari连接池参数配置
    hikari:
      minimum-idle: 5  # 最小空闲连接数
      maximum-pool-size: 15  # 最大连接池大小
      idle-timeout: 30000  # 空闲连接超时时间（毫秒）
      pool-name: HikariCP  # 连接池名称
      max-lifetime: 1800000  # 连接最大生命周期（毫秒）
      connection-timeout: 30000  # 连接超时时间（毫秒）
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库表结构
    show-sql: true  # 显示SQL语句
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8方言

# 日志配置
logging:
  # 日志文件路径
  file:
    name: logs/application.log
  # 日志级别
  level:
    root: INFO
    com.ggb.complete_set: DEBUG
  # 日志格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # 日志文件配置
  logback:
    rolling policy:
      # 单个日志文件最大大小
      max-file-size: 10MB
      # 日志文件保留天数
      max-history: 30
      # 日志文件总大小限制
      total-size-cap: 1GB

#%d{yyyy-MM-dd HH:mm:ss}: 时间戳，格式为年-月-日 时:分:秒
#[%thread]: 显示当前线程名
#%-5level: 日志级别（如INFO、DEBUG等），占5个字符宽度
#%logger{36}: 日志记录器的名称，最大长度36个字符
#%msg: 实际的日志消息内容
#%n: 换行符

#


